[package]
name = "smteepee"
version = "0.1.0"
authors = ["wakka <fungus.humungus@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1"
futures = "0.1"
regex = "1.1"
lazy_static = "1.3"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"

